<a href="https://colab.research.google.com/github/gugyeoj1n/Natural_Language_Processing/blob/main/08_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional

train_X = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]
train_X = np.array(train_X, dtype=np.float32)

rnn = SimpleRNN(3)
hidden_state = rnn(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))

rnn = SimpleRNN(3, return_sequences=True)
hidden_state = rnn(train_X)
print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))

rnn = SimpleRNN(3, return_sequences=True, return_state=True)
hidden_states, last_state = rnn(train_X)
print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))

hidden state : [[0.29832578 0.8831607  0.99058133]], shape: (1, 3)
hidden state : [[[ 0.9269081  -0.7836607   0.9985517 ]
  [ 0.98432666  0.64163715  0.93391585]
  [ 0.9306028  -0.8130228  -0.80031705]
  [ 0.99924487  0.48107034 -0.73630494]]], shape: (1, 4, 3)
hidden states : [[[ 0.8570359   0.01488924  0.7172787 ]
  [ 0.04610277 -0.71802986  0.0497513 ]
  [ 0.78999573 -0.96518004  0.25274518]
  [ 0.10556251 -0.92189056 -0.1744754 ]]], shape: (1, 4, 3)
last hidden state : [[ 0.10556251 -0.92189056 -0.1744754 ]], shape: (1, 3)
